// <copyright file="GlobalSuppressions.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.BasicTrackingPath")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.FlyingMonsters")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.FlyingMonsters")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.FlyingTrackingPath")]
[assembly: SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.GameAreaChar")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.GameAreaChar")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.Lavas")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.Lavas")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.Powerups")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.Powerups")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.Projectiles")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.Projectiles")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.ShootingMonsters")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.ShootingMonsters")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.TrackingMonsters")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.TrackingMonsters")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.Walls")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.Walls")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.Waters")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.IGameModel.Waters")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Not relevant.", Scope = "member", Target = "~M:Model.GameObjects.IsCollision(Model.GameObjects)~System.Boolean")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.GameModel.BasicTrackingPath")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.GameModel.FlyingMonsters")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.GameModel.FlyingTrackingPath")]
[assembly: SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.GameModel.GameAreaChar")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.GameModel.Lavas")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.GameModel.Powerups")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.GameModel.Projectiles")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.GameModel.ShootingMonsters")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.GameModel.TrackingMonsters")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.GameModel.Walls")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.GameModel.Waters")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Not relevant.", Scope = "member", Target = "~F:Model.Projectile.Direction")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "Not relevant.", Scope = "member", Target = "~F:Model.Projectile.Direction")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.Ui.HealthBar.HpBarX")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.Ui.HealthBar.HpBarY")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.Ui.HealthBar.HpHeight")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.Ui.HealthBar.HpWidth")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.Ui.LevelCounter.LvlCounterHeight")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.Ui.LevelCounter.LvlCounterWidth")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.Ui.LevelCounter.LvlCounterX")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Not relevant.", Scope = "member", Target = "~P:Model.Ui.LevelCounter.LvlCounterY")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "Not relevant.", Scope = "member", Target = "~F:Model.Active.BossEnemy.PlayerInSight")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Not relevant.", Scope = "member", Target = "~F:Model.Active.BossEnemy.PlayerInSight")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Not relevant.", Scope = "member", Target = "~F:Model.Active.BossEnemy.ShootingPattern")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "Not relevant.", Scope = "member", Target = "~F:Model.Active.BossEnemy.ShootingPattern")]
